#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "aeshin"
primary_region = "iad"
kill_signal = "SIGINT"
kill_timeout = "5s"

[build]
  dockerfile = "Dockerfile"

[env]
  PORT = "8000"

[mounts]
  source = "data"
  destination = "/mnt/data"
  processes = ["app"]

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0

  [http_service.concurrency]
    type = "connections"
    hard_limit = 25
    soft_limit = 20

  [[http_service.checks]]
    grace_period = "1s"
    interval = "15s"
    method = "GET"
    timeout = "2s"
    path = "/"
    protocol = "http"
    [http_service.checks.headers]
      Host = "aeshin.org"

[[statics]]
  guest_path = "/code/static"
  url_prefix = "/static/"
