app = "aeshin"
primary_region = "iad"

[build]

[env]
  PORT = "8000"

[mounts]
  source = "data"
  destination = "/mnt/data"
  processes = ["app"]

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = false
  auto_start_machines = false

[[statics]]
  guest_path = "/code/static"
  url_prefix = "/static/"

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
