"""
Markdown filter.
"""

from django import template
from django.conf import settings
from django.utils.encoding import force_str
from django.utils.safestring import mark_safe

import bleach
from bleach_whitelist import markdown_tags, markdown_attrs


register = template.Library()


def markdown(value, arg=''):
    """
    Runs Markdown over a given value.

    Syntax::

        {{ value|markdown:"unsanitized" }}

    To enable unsanitized mode, which allows raw HTML not generated by
    actual Markdown syntax, pass "unsanitized" as shown.
    """
    try:
        import markdown
    except ImportError:
        if settings.DEBUG:
            raise template.TemplateSyntaxError(
                "Error in {% markdown %} filter:"
                + " The python-markdown library isn't installed.")
        return force_str(value)
    else:
        unsanitized_html = markdown.markdown(force_str(value))

        if arg == 'unsanitized':
            return mark_safe(unsanitized_html)
        else:
            sanitized_html = bleach.clean(
                unsanitized_html,
                markdown_tags,
                markdown_attrs,
            )
            return mark_safe(sanitized_html)


markdown.is_safe = True

register.filter(markdown)
