"""
Markdown filter.
"""

from django import template
from django.conf import settings
from django.utils.encoding import force_str
from django.utils.safestring import mark_safe

import bleach
from markdown import extensions

markdown_tags = {
    "h1",
    "h2",
    "h3",
    "h4",
    "h5",
    "h6",
    "b",
    "i",
    "strong",
    "em",
    "tt",
    "p",
    "br",
    "span",
    "div",
    "blockquote",
    "code",
    "pre",
    "hr",
    "ul",
    "ol",
    "li",
    "dd",
    "dt",
    "img",
    "a",
    "sub",
    "sup",
}

markdown_attrs = {
    "*": ["id"],
    "img": ["src", "alt", "title"],
    "a": ["href", "alt", "title"],
}

register = template.Library()


def markdown(value, arg=""):
    """
    Runs Markdown over a given value.

    Syntax::

        {{ value|markdown:"unsanitized" }}

    To enable unsanitized mode, which allows raw HTML not generated by
    actual Markdown syntax, pass "unsanitized" as shown.
    """
    try:
        import markdown
    except ImportError as e:
        if settings.DEBUG:
            raise template.TemplateSyntaxError(
                "Error in {% markdown %} filter:"
                + " The python-markdown library isn't installed."
            ) from e
        return force_str(value)
    else:
        unsanitized_html = markdown.markdown(force_str(value), extensions=["extra"])

        if arg == "unsanitized":
            return mark_safe(unsanitized_html)
        else:
            sanitized_html = bleach.clean(
                unsanitized_html,
                markdown_tags,
                markdown_attrs,
            )
            return mark_safe(sanitized_html)


markdown.is_safe = True

register.filter(markdown)
