# Generated by Django 2.2.4 on 2019-09-26 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20190925_1618'),
    ]

    operations = [
        migrations.AddField(
            model_name='peerreviewsession',
            name='form_url',
            field=models.URLField(default='https://docs.google.com/forms/d/e/1FAIpQLSd55D3DjSt0bmdeaR6mkLxGY9MWg8A7mxqxVN-2FVC1tBybMA/viewform?usp=pp_url&entry.284655416='),
            preserve_default=False,
        ),
    ]
