# Generated by Django 2.2.4 on 2019-10-01 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_peerreviewsession_form_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='peerreview',
            name='state',
            field=models.PositiveSmallIntegerField(choices=[(0, 'New'), (2, 'In progress'), (3, 'Complete')], default=0),
        ),
    ]
