# Generated by Django 2.2.4 on 2019-10-01 20:39

from django.db import migrations


def migrate_state(apps, schema_editor):
    PeerReview = apps.get_model('courses', 'PeerReview')
    for review in PeerReview.objects.all():
        if review.in_progress:
            review.state = 1  # PeerReview.IN_PROGRESS
        else:
            review.state = 2  # PeerReview.COMPLETE
        review.save()


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_peerreview_state'),
    ]

    operations = [
        migrations.RunPython(migrate_state),
    ]
