# Generated by Django 2.2.4 on 2019-10-01 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_auto_20191001_1639'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='peerreview',
            name='in_progress',
        ),
    ]
