# Generated by Django 3.0.1 on 2020-01-04 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_remove_peerreview_in_progress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peerreview',
            name='state',
            field=models.PositiveSmallIntegerField(choices=[(0, 'New'), (1, 'In progress'), (2, 'Complete')], default=0),
        ),
    ]
