# Generated by Django 3.0.1 on 2020-01-04 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_auto_20200104_1330'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='instructors',
            field=models.ManyToManyField(related_name='courses_teaching', to='courses.Instructor'),
        ),
    ]
