# Generated by Django 3.0.1 on 2020-01-04 18:36

from django.db import migrations


def migrate_instructors(apps, schema_editor):
    Course = apps.get_model('courses', 'Course')
    for course in Course.objects.all():
        course.instructors.add(course.instructor)
        if course.assistant is not None:
            course.instructors.add(course.assistant)


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_course_instructors'),
    ]

    operations = [
        migrations.RunPython(migrate_instructors),
    ]
