# Generated by Django 3.0.1 on 2020-01-04 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_auto_20200104_1336'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='assistant',
        ),
        migrations.RemoveField(
            model_name='course',
            name='instructor',
        ),
    ]
