# Generated by Django 3.0.1 on 2020-01-04 20:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_auto_20200104_1458'),
    ]

    operations = [
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='units', to='courses.Course')),
                ('starts_with', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='starts_unit', to='courses.Meeting')),
            ],
        ),
    ]
