# Generated by Django 3.0.1 on 2020-01-05 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='recitations',
            field=models.TextField(blank=True),
        ),
    ]
