# Generated by Django 3.0.1 on 2020-01-05 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_unit_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='reading',
            name='centiwords',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
