# Generated by Django 3.0.1 on 2020-01-13 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0014_reading_centiwords'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='how_to_succeed',
            field=models.TextField(blank=True),
        ),
    ]
