# Generated by Django 3.0.1 on 2020-02-10 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0015_course_how_to_succeed'),
    ]

    operations = [
        migrations.AddField(
            model_name='peerreview',
            name='suggested_grade',
            field=models.SmallIntegerField(choices=[(-1, 'None'), (0, 'H'), (1, 'P'), (2, 'L'), (3, 'A+'), (4, 'A'), (5, 'A-'), (6, 'B+'), (7, 'B'), (8, 'B-'), (9, 'C+'), (10, 'C'), (11, 'C-'), (12, 'D+'), (13, 'D'), (14, 'F')], default=-1),
        ),
    ]
