# Generated by Django 3.0.1 on 2020-02-25 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0016_peerreview_suggested_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='letter_grade',
            field=models.CharField(blank=True, max_length=16),
        ),
    ]
