# Generated by Django 3.1 on 2020-08-10 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0019_readingassignment_is_optional'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Holiday',
            new_name='Milestone',
        ),
    ]
