# Generated by Django 3.1 on 2020-08-10 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0020_auto_20200810_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='milestone',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='courses.course'),
        ),
    ]
