# Generated by Django 3.1 on 2020-08-21 19:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0021_auto_20200810_1539'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReadingSummary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='courses/readings')),
                ('reading', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='summaries', to='courses.reading')),
                ('summarizer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
