# Generated by Django 3.1.4 on 2021-01-07 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0022_readingsummary'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReadingSummary',
        ),
    ]
