# Generated by Django 3.1.4 on 2021-01-07 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0024_course_is_weekly'),
    ]

    operations = [
        migrations.AddField(
            model_name='milestone',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
