# Generated by Django 3.1.4 on 2021-01-07 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0025_milestone_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
