# Generated by Django 4.1.6 on 2023-02-05 18:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0028_alter_course_location"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="peerreviewsession",
            name="assignment",
        ),
        migrations.RemoveField(
            model_name="course",
            name="blog_slug",
        ),
        migrations.RemoveField(
            model_name="course",
            name="ereserves_id",
        ),
        migrations.RemoveField(
            model_name="course",
            name="forum",
        ),
        migrations.RemoveField(
            model_name="course",
            name="thanks",
        ),
        migrations.RemoveField(
            model_name="reading",
            name="access_via_ereserves",
        ),
        migrations.RemoveField(
            model_name="readingassignment",
            name="discussion_leader",
        ),
        migrations.RemoveField(
            model_name="readingassignment",
            name="discussion_questions",
        ),
        migrations.RemoveField(
            model_name="submission",
            name="under_review",
        ),
        migrations.AlterField(
            model_name="assignment",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="readingassignment",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.DeleteModel(
            name="PeerReview",
        ),
        migrations.DeleteModel(
            name="PeerReviewSession",
        ),
    ]
