# Generated by Django 4.2.4 on 2023-08-15 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0030_assignment_is_inclass"),
    ]

    operations = [
        migrations.CreateModel(
            name="Building",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=80)),
                ("url", models.URLField()),
            ],
        ),
        migrations.RemoveField(
            model_name="course",
            name="recitations",
        ),
        migrations.AddField(
            model_name="course",
            name="room",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name="course",
            name="year",
            field=models.IntegerField(
                choices=[
                    (2011, "2011"),
                    (2012, "2012"),
                    (2013, "2013"),
                    (2014, "2014"),
                    (2015, "2015"),
                    (2016, "2016"),
                    (2017, "2017"),
                    (2018, "2018"),
                    (2019, "2019"),
                    (2020, "2020"),
                    (2021, "2021"),
                    (2022, "2022"),
                    (2023, "2023"),
                    (2024, "2024"),
                    (2025, "2025"),
                    (2026, "2026"),
                    (2027, "2027"),
                ]
            ),
        ),
        migrations.CreateModel(
            name="Recitation",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("times", models.CharField(max_length=64)),
                ("number", models.CharField(max_length=20)),
                ("room", models.CharField(max_length=20)),
                (
                    "building",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="courses.building",
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="recitations",
                        to="courses.course",
                    ),
                ),
                (
                    "instructor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="courses.instructor",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="course",
            name="building",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="courses.building",
            ),
        ),
    ]
