# Generated by Django 4.2.4 on 2023-08-20 21:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0032_milestone_end_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="meeting",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
