# Generated by Django 4.2.4 on 2023-08-22 17:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0033_alter_meeting_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="slides_are_called_notes",
            field=models.BooleanField(default=False),
        ),
    ]
