# Generated by Django 4.2.4 on 2023-08-23 00:52

import courses.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0034_course_slides_are_called_notes"),
    ]

    operations = [
        migrations.AddField(
            model_name="meeting",
            name="powerpoint",
            field=models.FileField(
                blank=True,
                null=True,
                storage=courses.models.FileSystemOverwriteStorage(),
                upload_to=courses.models.upload_pptx_to,
            ),
        ),
    ]
