# Generated by Django 5.0.1 on 2024-01-10 18:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0036_viewing_viewingassignment_meeting_viewings_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="github_url",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="course",
            name="zulip_url",
            field=models.URLField(blank=True),
        ),
    ]
