# Generated by Django 5.0.1 on 2024-01-11 16:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0037_course_github_url_course_zulip_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="communication",
            field=models.TextField(blank=True),
        ),
    ]
