# Generated by Django 5.1.4 on 2025-01-08 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0038_course_communication"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExternalCourse",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=80)),
                ("blurb", models.TextField(blank=True)),
                (
                    "semester",
                    models.CharField(
                        choices=[("sp", "Spring"), ("fa", "Fall")], max_length=2
                    ),
                ),
                (
                    "year",
                    models.IntegerField(
                        choices=[(2025, "2025"), (2026, "2026"), (2027, "2027")]
                    ),
                ),
                ("url", models.URLField()),
            ],
        ),
        migrations.AlterField(
            model_name="course",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
