# Generated by Django 5.2.2 on 2025-08-18 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0040_externalcourse_subtitle"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="subtitle",
            field=models.CharField(blank=True, max_length=80),
        ),
    ]
